### ISSUE TITLE
change solver from depth-first to breadth-first

### ISSUE THREAD

**Issue by runar-rkmedia** [runar-rkmedia/gotally#14]
This solver is depth-first, which is very bad since it is very likely that the a game can create
very deep branches with just some simple variations of swiping.
We should create a breadth-first implementation.
This could possible be done by have one function that evaluates once for all hints for the game, but does not 
actually do any work into these branches, but adds these into a queue, which is then performed.

For instance the generated game below goes to a depth of 5564. which is just ridiculous considering the board can be solved in 3 moves.

```toml
Name = '0130-current-paul-robin'
Preview = """

       0:    1:    2: 
 00: [  4 ][ 10 ][ 12 ]
 03: [  2 ][ 10 ][  8 ]
 06: [  1 ][  7 ][    ]"""
Hash = 'AwMECgwCCggBBwA='
Cells = [4, 10, 12, 2, 10, 8, 1, 7, 0]

[GeneratorOptions]
Rows = 3
Columns = 3
TargetCellValue = 64
MaxBricks = 9
MinBricks = 4
MinMoves = 0
MaxMoves = 7
MaxIterations = 100000000000
Concurrency = 1000
Seed = 0
MinGames = 100

[[Solutions]]
History = [[7, 6, 3, 4], [2, 5, 4], [0, 1, 4]]
HighestCellValue = 80
Score = 140
Moves = 3

[[Solutions]]
History = [[7, 6, 3, 4], [2, 5, 4], 'Right', [1, 2, 5]]
HighestCellValue = 80
Score = 140
Moves = 4

[[Solutions]]
History = [[7, 6, 3, 4], [2, 5, 4], 'Right', 'Down', 'Left', [3, 6, 7]]
HighestCellValue = 80
Score = 140
Moves = 6

[[Solutions]]
History = [[7, 6, 3, 4], [2, 5, 4], 'Right', 'Down', 'Left', 'Up', [3, 0, 1]]
HighestCellValue = 80
Score = 140
Moves = 7
```
